# Generated by Django 3.2.12 on 2022-02-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sellerregister',
            new_name='sellerregister_tb',
        ),
    ]
