# Generated by Django 3.2.12 on 2022-02-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_seller', '0002_rename_sellerregister_sellerregister_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregister_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
