# Generated by Django 3.2.12 on 2022-02-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_catagory_tb'),
        ('site_seller', '0003_sellerregister_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='')),
                ('catagoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.catagory_tb')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_seller.sellerregister_tb')),
            ],
        ),
    ]
