# Generated by Django 3.2.12 on 2022-03-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_seller', '0005_tracking_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
    ]
