# Generated by Django 3.2.12 on 2022-03-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_seller', '0006_alter_product_tb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='price',
            field=models.IntegerField(),
        ),
    ]
