# Generated by Django 3.2.12 on 2022-02-19 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_seller', '0004_product_tb'),
        ('site_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingaddress', models.CharField(max_length=20)),
                ('contactno', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_seller.product_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_user.register_tb')),
            ],
        ),
    ]
